use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Canonical specification for any artifact generated by or for the AI.
/// All binary content must be encoded (Hex/Base64); raw bytes are forbidden.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "ArtifactSpec")]
pub struct ArtifactSpec {
    /// The category of artifact, determining storage location and validation rules.
    pub kind: ArtifactType,
    
    /// Repository-relative path under artifacts/<kind>/.
    /// Must be sanitized: no "..", no absolute paths, no symlinks.
    pub filename: String,
    
    /// How the content field is encoded.
    pub encoding: ArtifactEncoding,
    
    /// The encoded payload. Never contains raw binary.
    pub content: String,
    
    /// Optional metadata for versioning and provenance.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ArtifactMetadata>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "ArtifactType")]
pub enum ArtifactType {
    /// Binary patch for N64 ROM, applied via starzip-cli
    N64RomPatch,
    /// Binary patch for PS1 ISO, applied via starzip-cli
    Ps1IsoPatch,
    /// Lua script for runtime injection via conk64-lua
    LuaScript,
    /// Input mapping configuration for controller bindings
    InputMapperConfig,
    /// Scenario definition for mission/objective logic
    ScenarioSpec,
    /// Narrative graph for branching story structures
    NarrativeGraph,
    /// Catch-all for experimental or custom artifact types
    Other,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "ArtifactEncoding")]
pub enum ArtifactEncoding {
    /// UTF-8 text (JSON, TOML, Lua source, etc.)
    Text,
    /// Hexadecimal encoding (2 chars per byte)
    Hex,
    /// Base64 encoding (standard, no padding required)
    Base64,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "ArtifactMetadata")]
pub struct ArtifactMetadata {
    /// Identifier of the base ROM/ISO this artifact modifies.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_rom_id: Option<String>,
    
    /// Identifier of the source recipe that generated this artifact.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_recipe_id: Option<String>,
    
    /// Expected size in bytes after decoding.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<u64>,
    
    /// Arbitrary key-value pairs for extensibility.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub custom: HashMap<String, serde_json::Value>,
}

/// Represents the state of a development session, providing context for AI decisions.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "SessionProfile")]
pub struct SessionProfile {
    /// Repository name being worked on.
    pub repo: String,
    
    /// Active Git branch.
    pub branch: String,
    
    /// Currently focused crate or module.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_crate: Option<String>,
    
    /// Enabled feature flags for this session.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub feature_flags: Vec<String>,
    
    /// Project-wide invariants that must be enforced.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub invariants: Vec<InvariantRule>,
    
    /// Status of recent CI runs, for adaptive AI behavior.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ci_status: Option<CiStatusReport>,
    
    /// Open TODO items extracted from code comments.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub todos: Vec<TodoItem>,
}

/// A rule that constrains what changes are permissible in a session.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "InvariantRule")]
pub struct InvariantRule {
    /// Unique identifier for this rule.
    pub rule_id: String,
    
    /// Human-readable description of the constraint.
    pub description: String,
    
    /// Scopes where this rule applies (crate paths, artifact kinds, etc.).
    pub scope: Vec<String>,
    
    /// How the rule is checked: static_analysis, size_ceiling, header_diff, etc.
    pub check: InvariantCheckType,
    
    /// Parameters for the check implementation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "InvariantCheckType")]
pub enum InvariantCheckType {
    /// Run a static analysis tool (clippy, custom linter)
    StaticAnalysis,
    /// Enforce a size ceiling on artifacts
    SizeCeiling,
    /// Compare generated headers against a baseline
    HeaderDiff,
    /// Validate determinism via replay harness
    DeterminismReplay,
    /// Custom check implemented in Rust
    Custom,
}

/// Summary of recent CI pipeline execution.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "CiStatusReport")]
pub struct CiStatusReport {
    /// Unique identifier for the CI run.
    pub run_id: String,
    
    /// Overall status: passed, failed, cancelled.
    pub status: CiStatus,
    
    /// Timestamp of run completion.
    pub completed_at: String,
    
    /// Structured failures for AI to learn from.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub failures: Vec<CiFailure>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "CiStatus")]
pub enum CiStatus {
    Passed,
    Failed,
    Cancelled,
}

/// A single failure from a CI run, with context for remediation.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "CiFailure")]
pub struct CiFailure {
    /// Name of the job or step that failed.
    pub job: String,
    
    /// Error message or assertion that failed.
    pub message: String,
    
    /// File path and line number if applicable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<FailureLocation>,
    
    /// Suggested fix or reference to documentation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suggestion: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "FailureLocation")]
pub struct FailureLocation {
    pub file: String,
    pub line: Option<u32>,
    pub column: Option<u32>,
}

/// A TODO item extracted from source code comments.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[schemars(rename = "TodoItem")]
pub struct TodoItem {
    /// Source file containing the TODO.
    pub file: String,
    
    /// Line number of the TODO comment.
    pub line: u32,
    
    /// The TODO text itself.
    pub text: String,
    
    /// Optional priority or category tag.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}
