// crates/gamemodeai-build/src/main.rs

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, Result};
use clap::Parser;
use jsonschema::{Draft, JSONSchema};
use serde_json::Value as JsonValue;

use recipes::arena_n64::GameRecipe;

#[derive(Parser, Debug)]
#[command(name = "gamemodeai-build")]
#[command(version)]
#[command(about = "Build N64 arena shooter ROMs from GAMEMODE.ai recipes")]
struct Args {
    /// Path to the recipe JSON file
    #[arg(long)]
    recipe: PathBuf,

    /// Output directory for intermediate data and final ROM
    #[arg(long, default_value = "build")]
    out_dir: PathBuf,
}

fn main() -> Result<()> {
    let args = Args::parse();

    // 1. Load recipe JSON as untyped value
    let recipe_raw = fs::read_to_string(&args.recipe)
        .with_context(|| format!("Failed to read recipe at {}", args.recipe.display()))?;
    let recipe_value: JsonValue = serde_json::from_str(&recipe_raw)
        .with_context(|| "Failed to parse recipe as JSON value")?;

    // 2. Load JSON Schema generated by schemars
    let schema_path = Path::new("schemas").join("arena_n64_game_recipe.schema.json");
    let schema_data = fs::read_to_string(&schema_path)
        .with_context(|| format!("Failed to read schema at {}", schema_path.display()))?;
    let schema_json: JsonValue = serde_json::from_str(&schema_data)
        .with_context(|| "Failed to parse schema JSON")?;

    // 3. Validate recipe against schema
    let compiled = JSONSchema::options()
        .with_draft(Draft::Draft7) // schemars default
        .compile(&schema_json)
        .with_context(|| "Failed to compile JSON schema")?;

    if let Err(errors) = compiled.validate(&recipe_value) {
        eprintln!("Recipe validation failed:");
        for err in errors {
            eprintln!("- at {}: {}", err.instance_path, err);
        }
        anyhow::bail!(
            "Recipe is not valid according to arena_n64_game_recipe.schema.json"
        );
    }

    // 4. Safe to deserialize into strongly-typed struct
    let recipe: GameRecipe = serde_json::from_value(recipe_value)
        .with_context(|| "Failed to deserialize GameRecipe from validated JSON")?;

    // 5. Basic semantic validation
    validate_recipe(&recipe)?;

    // 6. Prepare output directories
    fs::create_dir_all(&args.out_dir)
        .with_context(|| format!("Failed to create out_dir {}", args.out_dir.display()))?;
    let data_dir = args.out_dir.join("data");
    let assets_dir = args.out_dir.join("assets");
    fs::create_dir_all(&data_dir)?;
    fs::create_dir_all(&assets_dir)?;

    // 7. Generate engine config files
    generate_engine_configs(&recipe, &data_dir)?;

    // 8. Stage assets for conversion (currently just copies; extend with real conversion)
    stage_assets(&recipe, &assets_dir)?;

    // 9. Invoke N64 toolchain
    match recipe.build.toolchain.kind.as_str() {
        "nust64" => build_with_nust64(&recipe, &args.out_dir)?,
        "n64chain" => build_with_n64chain(&recipe, &args.out_dir)?,
        other => anyhow::bail!("Unsupported toolchain kind: {other}"),
    }

    println!(
        "Build complete: {}",
        args.out_dir.join(&recipe.build.rom_name).display()
    );
    Ok(())
}

fn validate_recipe(recipe: &GameRecipe) -> Result<()> {
    if recipe.template != "arenashooter_n64_v1" {
        anyhow::bail!("Unsupported template: {}", recipe.template);
    }
    if recipe.build.target != "n64" {
        anyhow::bail!("Unsupported build target: {}", recipe.build.target);
    }
    if recipe.weapons.is_empty() {
        anyhow::bail!("Recipe must define at least one weapon");
    }
    if recipe.maps.is_empty() {
        anyhow::bail!("Recipe must define at least one map");
    }
    // Add more constraints: max players, tile sizes, etc.
    Ok(())
}

fn generate_engine_configs(recipe: &GameRecipe, data_dir: &Path) -> Result<()> {
    // In a real engine, these would match your ECS config loaders.
    let rules_path = data_dir.join("rules.json");
    let rules_json = serde_json::to_string_pretty(&recipe.rules)?;
    fs::write(&rules_path, rules_json)?;

    let weapons_path = data_dir.join("weapons.json");
    let weapons_json = serde_json::to_string_pretty(&recipe.weapons)?;
    fs::write(&weapons_path, weapons_json)?;

    let maps_path = data_dir.join("maps.json");
    let maps_json = serde_json::to_string_pretty(&recipe.maps)?;
    fs::write(&maps_path, maps_json)?;

    let enemies_path = data_dir.join("enemies.json");
    let enemies_json = serde_json::to_string_pretty(&recipe.enemies)?;
    fs::write(&enemies_path, enemies_json)?;

    let music_path = data_dir.join("music.json");
    let music_json = serde_json::to_string_pretty(&recipe.music)?;
    fs::write(&music_path, music_json)?;

    Ok(())
}

fn stage_assets(recipe: &GameRecipe, assets_dir: &Path) -> Result<()> {
    // For now, just ensure referenced asset files exist; later, run conversion pipelines.
    for tileset in &recipe.assets.tilesets {
        let src = Path::new(&tileset.source);
        let dest = assets_dir.join(&tileset.source);
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::copy(src, &dest).with_context(|| {
            format!(
                "Failed to copy tileset from {} to {}",
                src.display(),
                dest.display()
            )
        })?;
    }

    for sprite in &recipe.assets.sprites {
        let src = Path::new(&sprite.source);
        let dest = assets_dir.join(&sprite.source);
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::copy(src, &dest).with_context(|| {
            format!(
                "Failed to copy sprite from {} to {}",
                src.display(),
                dest.display()
            )
        })?;
    }

    for track in &recipe.music.tracks {
        let src = Path::new(&track.source);
        let dest = assets_dir.join(&track.source);
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::copy(src, &dest).with_context(|| {
            format!(
                "Failed to copy music from {} to {}",
                src.display(),
                dest.display()
            )
        })?;
    }

    Ok(())
}

// --- Toolchain integration stubs -------------------------------------------
// Implement these based on your chosen N64 toolchain setup.

fn build_with_nust64(recipe: &GameRecipe, out_dir: &Path) -> Result<()> {
    let project_root = Path::new("n64game");
    let resources_dir = project_root.join("resources");
    if resources_dir.exists() {
        fs::remove_dir_all(&resources_dir)?;
    }
    fs::create_dir_all(&resources_dir)?;

    let source_data = out_dir.join("data");
    let source_assets = out_dir.join("assets");
    copy_dir_all(&source_data, &resources_dir.join("data"))?;
    copy_dir_all(&source_assets, &resources_dir.join("assets"))?;

    let status = Command::new("nust64")
        .current_dir(&project_root)
        .arg("run")
        .arg("--profile")
        .arg(&recipe.build.toolchain.profile)
        .arg("--output")
        .arg(out_dir.join(&recipe.build.rom_name))
        .status()
        .with_context(|| "Failed to invoke nust64")?;

    if !status.success() {
        anyhow::bail!("nust64 failed with status: {}", status);
    }

    Ok(())
}

fn build_with_n64chain(recipe: &GameRecipe, out_dir: &Path) -> Result<()> {
    let project_root = Path::new("n64libdragon");
    let fs_dir = project_root.join("filesystem");
    if fs_dir.exists() {
        fs::remove_dir_all(&fs_dir)?;
    }
    fs::create_dir_all(&fs_dir)?;

    let source_data = out_dir.join("data");
    let source_assets = out_dir.join("assets");
    copy_dir_all(&source_data, &fs_dir.join("data"))?;
    copy_dir_all(&source_assets, &fs_dir.join("assets"))?;

    let status = Command::new("libdragon")
        .arg("make")
        .current_dir(&project_root)
        .status()
        .with_context(|| "Failed to invoke libdragon make")?;

    if !status.success() {
        anyhow::bail!("libdragon make failed with status: {}", status);
    }

    let built_rom = project_root.join("build").join("game.z64");
    fs::copy(&built_rom, out_dir.join(&recipe.build.rom_name))
        .with_context(|| "Failed to copy built ROM")?;

    Ok(())
}

fn copy_dir_all(src: &Path, dst: &Path) -> Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if file_type.is_dir() {
            copy_dir_all(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}
